### PR TITLE
add circom just

### PR DESCRIPTION
**Pull request by kziemianek**
You can install just by `cargo install just`.
Looks like a very handy tool to organise these commands. For example you can run whole tau ceremony just by typing `just tau`

### CODE REVIEW

**Comment by mgralinski-bright** [comment]
1. Please change the output dir for all artefacts to the `build` directory (now I got an error: "[ERROR] snarkJS: [Error: ENOENT: no such file or directory, open 'build/task.r1cs']"
2. Add this command and setup to the documentation

**Comment by mgralinski-bright** [comment]
When I type `just tau` i get an error `[ERROR] snarkJS: [Error: ENOENT: no such file or directory, open 'task.r1cs']`

**Comment by kziemianek** [comment]
you need to build circuit before

**Comment by mgralinski-bright** [comment]
Ok, it looks fine. I would only suggest to add one more command like: `just test` to run all commands, but it's up to you.

**Review by mgralinski-bright — APPROVED** [review]

**Pull request merged**
